### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by xJkaay** [WWolf-dev/ww-blipsBuilder#1]
is there an Sql for this script bc my database says its missing stuff

**Comment by WWolf-dev** [comment]
Hey, yes it should be Inside the folder and if its not let me update the repo on GitHubKind regards,White Wolf De : xJkaayEnvoyé le :samedi 23 septembre 2023 22:02À : WWolf-dev/ww-blipsBuilderCc : SubscribedObjet :[WWolf-dev/ww-blipsBuilder] SQL (Issue #1) is there an Sql for this script bc my database says its missing stuff—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by WWolf-dev** [comment]
Hey, my bad for the miss, i just put it in the repo you can re download it without any issue

**Comment by WWolf-dev** [comment]
Is it good now ?

**Comment by xJkaay** [comment]
i just redownloaded it  im gonna test it

**Comment by WWolf-dev** [comment]
okay i wait tell me

**Comment by xJkaay** [comment]
when the server restarts and a player joins the blips arent there
i have to restart the script everytime someone joins

**Comment by WWolf-dev** [comment]
okay let me fix that

**Comment by WWolf-dev** [comment]
I fixed it you can re download or just look at the last commit and add the line that I added

**Comment by WWolf-dev** [comment]
Tell me if everything is good now it should be

**Comment by xJkaay** [comment]
it worked everything is all good

**Comment by WWolf-dev** [comment]
Perfect, if you need anything else come on my discord and dm me or open an other issue have a great day
